apiVersion: batch/v1
kind: Job
metadata:
  namespace: training-workloads # DO NOT CHANGE
  generateName: ###### ENTER TASK NAME HERE ######
  annotations:
    kueue.x-k8s.io/queue-name: training-workloads # DO NOT CHANGE
spec:
  ttlSecondsAfterFinished: 60 # job will be deleted after 60 seconds post completion
  parallelism: 1 # how many replicas to run
  completions: 1 # how many replicas to run to completion
  suspend: true # setting to true to allow kueue to manage
  template:
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-a100" ###### ENTER GPU HERE ######
      containers:
      - name: wasting-gpu-compute-time-baby
        image: us-west1-docker.pkg.dev/pc464-mas-fvs/pangaea-bench/base:latest # link to artifact storage link
        command: ["torchrun", "--flag", "flag-value"] ###### ENTER ENTRY COMMAND HERE ######
        args: ["arg"]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "512Mi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "500m"
            memory: "512Mi"
            ephemeral-storage: "512Mi"
            nvidia.com/gpu: "1"
      restartPolicy: Never
    volumeMounts:
    - name: gcs-fuse-csi-vol # this must match the volume name below
      mountPath: /data ###### ENTER MOUNT PATH HERE ####
      readOnly: false
  serviceAccountName: training-workloads # DO NOT CHANGE
  volumes:
  - name: gcs-fuse-csi-vol
    csi:
      driver: gcsfuse.csi.storage.gke.io
      readOnly: false
      volumeAttributes:
        bucketName: your-bucket-name-here ###### ENTER BUCKET NAME HERE ###### 
        mountOptions: "implicit-dirs"