HYDRA_FULL_ERROR=1 torchrun pangaea/run.py \
    --config-name=train \
    dataset=dynamicen \
    encoder=terramind_large \
    decoder=seg_upernet_mt_ltae \
    preprocessing=seg_default \
    criterion=cross_entropy \
    task=segmentation \
    limited_label_train=0.1 \
    limited_label_strategy=stratified