train:
    _target_: pangaea.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd

val:
    _target_: pangaea.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd

test:
    _target_: pangaea.engine.data_preprocessor.Preprocessor
    preprocessor_cfg:
        - _target_: pangaea.engine.data_preprocessor.NormalizeMeanStd