_target_: pangaea.datasets.faofra.FAOFRACd
dataset_name: FAOFRACd
root_path: ./data/faofracd
download_url: https://the-dataset-is-not-publicly-available.com
auto_download: False
img_size: 32
gezs: [11,12,13,14,15,16]
n_timepoints: 2
seed: 42
test_size: 0.2
val_size: 0.2
shuffle: true

multi_temporal: True
multi_modal: False

# classes
ignore_index: -1
num_classes: 4
classes:
  - ForestGain
  - ForestLoss
  - StableForest
  - StableNonForest
distribution:
  - 0.13608247 
  - 0.21134021 
  - 0.32474227 
  - 0.32783505

bands:
  optical:
    - B2
    - B3
    - B4
    - B8A
    - B11
    - B12
data_mean:
  optical:
    - 0.05509873 
    - 0.08855352 
    - 0.10817418 
    - 0.28396659 
    - 0.26407967 
    - 0.16970162
data_std:
  optical:
    - 0.0358508  
    - 0.05825059 
    - 0.09421124 
    - 0.08169411 
    - 0.12540554 
    - 0.12450739
data_min:
  optical: [-0.03179625, -0.00132625, 0., 0., 0.,0.]
data_max:
  optical: [0.28983, 0.3918825, 0.5384025, 0.62297875, 1.6022125, 0.67762125]