_target_: pangaea.datasets.geobench.meurosat.mEuroSat  
dataset_name: mEuroSat
root_path: ${oc.env:GEO_BENCH_DIR}/classification_v1.0/m-eurosat  # ensure sys env var GEO_BENCH_DIR exist
download_url: "recursix/geo-bench-1.0"
auto_download: True
ignore_index: -100
multi_temporal: False
multi_modal: False
img_size: 64
num_classes: 10

bands:
  optical:
    - B1
    - B2
    - B3
    - B4
    - B5
    - B6
    - B7
    - B8
    - B8A
    - B9
    - B10
    - B11
    - B12

classes: ['AnnualCrop', 'Forest', 'HerbaceousVegetation', 'Highway', 'Industrial', 'Pasture', 'PermanentCrop', 'Residential', 'River', 'SeaLake']
distribution: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


data_mean:
  optical: [1355.5426, 1113.8855, 1035.7394, 928.2619, 1188.2629, 2032.7325, 2416.5286, 2342.5396, 748.9036, 12.0419, 1810.1284, 1101.3801, 2644.5996]
data_std:
  optical: [68.9288, 160.0012, 194.6687, 286.8012, 236.6991, 372.3853, 478.1329, 556.7527, 102.5583, 1.2167, 392.9388, 313.7339, 526.7788]

data_min:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
data_max:
  optical: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]