_target_: pangaea.datasets.geobench.mforestnet.mForestnet
dataset_name: mForestnet
root_path: ${oc.env:GEO_BENCH_DIR}/classification_v1.0/m-forestnet
download_url: "recursix/geo-bench-1.0"
auto_download: True

num_classes: 12
img_size: 332
multi_temporal: False
multi_modal: False

ignore_index: -100
classes:  [
    "Oil palm plantation",
    "Timber plantation",
    "Other large-scale plantations",
    "Grassland shrubland",
    "Small-scale agriculture",
    "Small-scale mixed plantation",
    "Small-scale oil palm plantation",
    "Mining",
    "Fish pond",
    "Logging",
    "Secondary forest",
    "Other",
]

distribution: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

# data stats
bands:
  optical:   # 6 bands from Landsat, but band names here are corresponding to Sentinel-2
    - B2
    - B3
    - B4
    - B8
    - B11
    - B12

data_mean:
  optical: [72.852258, 83.677155, 77.58181, 123.987442, 91.536942, 74.719202]
data_std:
  optical: [15.837172547567825, 14.788812599596188, 16.100543441881086, 16.35234883118129, 13.7882739778638, 12.69131413539181]

data_min:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
data_max:
  optical: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]