_target_: pangaea.datasets.geobench.mpv4ger.mPv4ger
dataset_name: mPv4ger
root_path: ${oc.env:GEO_BENCH_DIR}/classification_v1.0/m-pv4ger
download_url: "recursix/geo-bench-1.0"
auto_download: True

num_classes: 2
img_size: 320
multi_temporal: False
multi_modal: False

ignore_index: -100
classes:  ["no solar pv", "solar pv"]
distribution: [0, 0]

# data stats
bands:
  optical:
    - B4
    - B3
    - B2

data_mean:
  optical: [113.385309, 119.65935, 116.628328]
data_std:
  optical: [54.19692448815262, 48.282311849967364, 44.668890717415586]
data_min:
  optical: [0.0, 0.0, 0.0]
data_max:
  optical: [255.0, 255.0, 255.0]