_target_: pangaea.datasets.spacenet7.SN7MAPPING
dataset_name: SN7MAPPING
root_path: ./data/spacenet7
download_url: https://drive.google.com/uc?id=1BADSEjxYKFZZlM-tEkRUfHvHi5XdaVV9
auto_download: True

img_size: 256  # the image size is used to tile the SpaceNet 7 images (1024, 1024)
domain_shift: True
# parameters for within-scene splits (no domain shift)
i_split: 768
j_split: 512

multi_temporal: False
multi_modal: False

# classes
ignore_index: -1
num_classes: 1
classes:
  - Background
  - Building
distribution:
  - 0.92530769
  - 0.07469231

# data stats
bands:
  optical:
    - B4  # Band 1 (Red)
    - B3  # Band 2 (Green)
    - B2  # Band 3 (Blue)
data_mean:
  optical:
    - 121.826
    - 106.52838
    - 78.372116
data_std:
  optical:
    - 56.717068
    - 44.517075
    - 40.451515
data_min:
  optical: [0.0, 0.0, 0.0]
data_max:
  optical: [255.0, 255.0, 255.0]