train: false
work_dir: ""
seed: 234
use_wandb: false

# TRAINING
num_workers: 1
batch_size: 1

test_num_workers: 0
test_batch_size: 1


# EXPERIMENT
use_final_ckpt: false
finetune: false
data_replicate: 1
ckpt_dir: ???
embed_dir: './embeddings'
out_dir: './umap_knn'


defaults:
  - task: ???
  - dataset: ???
  - _self_
