train: false
work_dir: ""
seed: 234
use_wandb: false

# TRAINING
num_workers: 1
batch_size: 1

test_num_workers: 0
test_batch_size: 1


# EXPERIMENT
use_final_ckpt: false
finetune: false
data_replicate: 1
ckpt_dir: ???
embed_dir: './embeddings'
out_dir: './umap_knn'

label_file_subset: 30
umap_n_neighbors: 20
umap_min_dist: 0.5
umap_spread: 1
umap_n_components: 2
 

defaults:
  - task: ???
  - dataset: ???
  - encoder: ???
  - decoder: ???
  - preprocessing: ??
  - criterion: ???
  - _self_
