train: true
work_dir: "./checkpoints/"
seed: 234
use_wandb: true
wandb_run_id: null
pretrained: true

# TRAINING
num_workers: 0
batch_size: 8

test_num_workers: 0
test_batch_size: 1

# EXPERIMENT
finetune: false
ckpt_dir: null
limited_label_train: 1
limited_label_val: 1
limited_label_strategy: stratified  # Options: stratified, oversampled, random
stratification_bins: 3 #  number of bins for stratified sampling, only for stratified
data_replicate: 1
use_final_ckpt: false
emebed: true


defaults:
  - task: ???
  - dataset: ???
  - encoder: ???
  - decoder: ???
  - preprocessing: ???
  - criterion: ???
  - lr_scheduler: multi_step_lr
  - optimizer: adamw
  - _self_ 
