_target_: pangaea.decoders.fcn.FCNDecoder

# overwritten in run
encoder: null
finetune: ${finetune}

# to adapt
channels: 1024
num_classes: ${dataset.num_classes}

num_convs: 4
kernel_size: 3
concat_input: true
dilation: 1
interp_method: PixelShuffle